-- This file has been generated by Dungeon Editor 2.1.9

-- TODO: place your custom dungeon object definitions here

defineObject{
   name = "forest_exit_teleporter",
   baseObject = "forest_stairs_down",
   components = {
      {
         class = "Item",
         uiName = "forest_exit_teleporter",
         description = "An exit that will teleport the player were ever!",
      }
   },
}
